# Generated by Django 5.0.4 on 2024-04-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apt',
        ),
    ]
