# Generated by Django 5.0.4 on 2024-04-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_apt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
