# Generated by Django 5.0.4 on 2024-04-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_coords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coords',
        ),
    ]
