# Generated by Django 5.0.4 on 2024-04-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_coords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coords',
        ),
    ]
