# Generated by Django 5.0.4 on 2024-05-10 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=2083)),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apt')),
            ],
        ),
    ]
